---

openvpn_etcdir: /etc/openvpn
openvpn_keydir: "{{ openvpn_etcdir }}/keys"

# Default settings (See OpenVPN documentation)
openvpn_host: "{{ ec2_private_ip_address }}" # or inventory_hostname
openvpn_port: 1194
openvpn_proto: udp
openvpn_dev: tun
openvpn_network: 10.10.0.0
openvpn_subnetmask: 255.255.255.0
openvpn_server: "{{ openvpn_network }} {{ openvpn_subnetmask }}" # skip when empty
openvpn_max_clients: 100
openvpn_log: /var/log/openvpn.log
openvpn_keepalive: "10 120"
openvpn_ifconfig_pool_persist: ipp.txt
openvpn_comp_lzo: yes
openvpn_status: openvpn-status.log
openvpn_verb: 3
openvpn_user: nobody
openvpn_group: nogroup
openvpn_resolv_retry: infinite
openvpn_client_to_client: yes
openvpn_allow_internet_access: 1

openvpn_key_country: US
openvpn_key_province: PA
openvpn_key_city: Philadelphia
openvpn_key_org: Access-Abundant
openvpn_key_email: we@ana.io
openvpn_key_size: 1024

openvpn_clients: [client] # make clients certificate
openvpn_clients_revoke: [] # revoke clients certificates

# Use PAM authentication
# If empty use system users
# otherwise use users from the option
# openvpn_use_pam_users:
# - { name: user, password: password }

openvpn_use_pam: yes
openvpn_use_pam_users:
    - { name: username, password: secret }

# LDAP authentication and configuration (optional)
openvpn_use_ldap: no
openvpn_ldap_tlsenable: 'no'
openvpn_ldap_follow_referrals: 'no'

# OpenVPN PAM libraries
openvpn_use_pam_plugin_distribution:  /usr/lib/openvpn/openvpn-plugin-auth-pam.so
openvpn_use_ldap_plugin_distribution: /usr/lib/openvpn/openvpn-auth-ldap.so

# Server Additional Config Options
openvpn_server_options:
    - 'push "redirect-gateway def1 bypass-dhcp"'
    - 'push "route 172.31.0.0 255.255.255.0"'
    - 'push "dhcp-option WINS {{ openvpn_host }}"'
    - 'push "dhcp-option DNS  {{ openvpn_host }}"'
    - 'push "dhcp-option DNS 8.8.8.8"'
    - 'push "dhcp-option DNS 8.8.4.4"'
    - 'push "route-method exe"'
    - 'push "route-delay 2"'

# Client Additional Config Options
openvpn_client_options:
    - "down /etc/openvpn/update-resolv-conf"
    - "up /etc/openvpn/update-resolv-conf"
    - "script-security 3"

