---

- name: create the {{ servicename }} group
  sudo: yes
  group: name={{ servicename }} state=present

- name: create the {{ servicename }} user
  sudo: yes
  user: name={{ servicename }} group={{ servicename }} shell=/bin/bash 

- name: add {{ servicename }} user to sudoers
  lineinfile: dest=/etc/sudoers
              backup=yes
              state=present
              regexp='^%{{ servicename }}'
              insertafter="^%sudo"
              line='%{{ servicename }} ALL=(ALL) ALL'
