---

- name: enabling nginx site with proxy {{ sitename }}
  sudo: yes
  file: src=/etc/nginx/sites-available/{{ sitename }}
        dest=/etc/nginx/sites-enabled/{{ sitename }}
        owner=root
        group=root
        state=link
        force=yes
